# Use the official Node.js image as the base image
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the app.js file to the working directory
COPY app.js .

# Command to run the app.js script
CMD ["node", "app.js"]

